"""initial schema

Revision ID: 26c6ae714cf2
Revises:
Create Date: 2026-07-25 19:36:12.528847

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '26c6ae714cf2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('legal_id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('admin_email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('confirmation_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legal_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('residents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('admission_reason', sa.Text(), nullable=True),
    sa.Column('room_number', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('id_type', sa.String(), nullable=True),
    sa.Column('id_number', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_country', sa.String(), nullable=False),
    sa.Column('birth_place', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('civil_status', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('education_level', sa.String(), nullable=True),
    sa.Column('religion', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('social_security_system', sa.String(), nullable=True),
    sa.Column('social_security_company', sa.String(), nullable=True),
    sa.Column('social_security_company_phone', sa.String(), nullable=True),
    sa.Column('has_funeral_service', sa.String(), nullable=True),
    sa.Column('funeral_service_name', sa.String(), nullable=True),
    sa.Column('funeral_service_phone', sa.String(), nullable=True),
    sa.Column('guardians', sa.JSON(), nullable=False),
    sa.Column('children_number', sa.Integer(), nullable=True),
    sa.Column('male_children_number', sa.Integer(), nullable=True),
    sa.Column('female_children_number', sa.Integer(), nullable=True),
    sa.Column('children_address', sa.String(), nullable=True),
    sa.Column('children_phone', sa.String(), nullable=True),
    sa.Column('is_good_family_environment', sa.String(), nullable=True),
    sa.Column('family_environment_description', sa.Text(), nullable=True),
    sa.Column('can_live_in_community', sa.String(), nullable=True),
    sa.Column('why_can_live_in_community', sa.Text(), nullable=True),
    sa.Column('has_participated_in_community_groups', sa.String(), nullable=True),
    sa.Column('why_has_participated_in_community_groups', sa.Text(), nullable=True),
    sa.Column('spare_time_activities', sa.JSON(), nullable=False),
    sa.Column('spare_time_activities_other', sa.String(), nullable=True),
    sa.Column('economic_aspect', sa.String(), nullable=True),
    sa.Column('medical_background', sa.JSON(), nullable=True),
    sa.Column('functional_assessment', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_residents_company_id_full_name', 'residents', ['company_id', 'full_name'], unique=False)
    op.create_index('ux_residents_company_id_id_number', 'residents', ['company_id', 'id_number'], unique=True, sqlite_where=sa.text('id_number IS NOT NULL'))
    op.create_table('nursing_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resident_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('shift', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('nurse_id', sa.String(length=36), nullable=False),
    sa.Column('nurse_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nursing_notes')
    op.drop_index('ux_residents_company_id_id_number', table_name='residents', sqlite_where=sa.text('id_number IS NOT NULL'))
    op.drop_index('ix_residents_company_id_full_name', table_name='residents')
    op.drop_table('residents')
    op.drop_table('users')
    op.drop_table('companies')
    # ### end Alembic commands ###
